### ISSUE TITLE
Loss division by 4

### ISSUE THREAD

**Issue by marijnl** [littleredxh/EasyPositiveHardNegative#2]
Im a bit confused by this line:
https://github.com/littleredxh/EasyPositiveHardNegative/blob/master/_code/Loss.py#L80

Why do you divide the loss by a constant here? In the logging its divided by N but the final loss calculation uses a constant.

**Comment by littleredxh** [comment]
Sorry for this version, I modified the code to adapt multi-gpu training, 4 means 4 gpus. I will fix it later
